thegoodparty/gp-api

- README.md
- package-lock.json
- package.json
- src/main.ts
> Web 3243 swagger

- .eslintrc.js
- .prettierrc
- package.json
- src/app.controller.spec.ts
- src/app.controller.ts
- src/app.module.ts
- src/app.service.ts
- src/content/content.controller.spec.ts
- src/content/content.controller.ts
- src/content/content.module.ts
- src/content/content.service.spec.ts
- src/content/content.service.ts
- src/content/dto/create-content.dto.ts
- src/content/dto/update-content.dto.ts
- src/content/entities/content.entity.ts
- src/main.ts
- test/app.e2e-spec.ts
Postman test result: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-f41c7a34-e602-4ff6-885d-ed955edd47ba
Also adds prettier rule to allow us to write code w/o needing `;`'s
> [WEB-3320] - Content Module Scaffolding

- package.json
- src/app.module.ts
- src/health/health.controller.ts
- src/health/health.module.ts
- src/health/health.service.ts
Test run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-a1a44e28-6830-45c6-8540-24b067583d4b
> [WEB-3343] - health check endpoint

- api/package.json
- api/seed/campaigns.ts
- api/seed/factories/campaign.factory.ts
- api/seed/seed.ts
Update to run seeds through prisma
> WEB-3375: Implement prisma seed

- .env.example
- package-lock.json
- package.json
- src/app.module.ts
- src/payments/payments.module.ts
- src/payments/purchase/purchase.controller.ts
- src/payments/stripe/stripe.service.ts
https://goodparty.atlassian.net/browse/WEB-3388
Tests: https://goodpartyorg.postman.co/workspace/66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-64e44c1a-ae72-48ea-af84-ea20d5d89b8d
> [WEB-3388] - Create checkout session

- .env.example
- .eslintrc.js
- prisma/migrations/20250103175250_add_ai_chat/migration.sql
- prisma/schema/aiChat.jsonTypes.ts
- prisma/schema/aiChat.prisma
- prisma/schema/campaign.prisma
- prisma/schema/user.prisma
- seed/campaigns.ts
- src/ai/ai.service.ts
- src/ai/ai.types.ts
- src/campaigns/ai/campaignsAi.module.ts
- src/campaigns/ai/chat/aiChat.controller.ts
- src/campaigns/ai/chat/aiChat.service.ts
- src/campaigns/ai/chat/aiChat.types.ts
- src/campaigns/ai/chat/schemas/AiChatFeedback.schema.ts
- src/campaigns/ai/chat/schemas/CreateAiChat.schema.ts
- src/campaigns/ai/chat/schemas/UpdateAiChat.schema.ts
- src/campaigns/ai/chat/util/buildSlackBlocks.util.ts
- src/campaigns/ai/content/aiContent.controller.ts
- src/campaigns/ai/content/aiContent.service.ts
- src/campaigns/ai/schemas/CreateAiContent.schema.ts
- src/campaigns/campaigns.types.ts
- src/content/content.service.ts
- src/graphql/graphql.module.ts
- src/queue/consumer/consumer.service.ts
- src/races/races.module.ts
Migrates the Ai Chat create, update, get, list, delete, and feedback endpoints
Postman tests: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-d05625d8-97a2-4fda-a3f2-d83cde4adcb1
> WEB-3359: Nestjs - migrate campaign chat CRUD + feedback

- src/admin/admin.module.ts
- src/admin/users/adminUsers.controller.ts
- src/admin/users/schemas/AdminCreateUser.schema.ts
- src/admin/users/schemas/AdminUserList.schema.ts
- src/campaigns/services/campaigns.service.ts
- src/shared/types/utility.types.ts
- src/users/users.controller.ts
- src/users/users.service.ts
**NOTE: based on #45**
migrates admin user list, create, and delete endpoints.
[Postman Tests](https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-91ff4916-f4a5-4d3f-adb0-a57e16141a06)
> WEB-3422: NestJS - migrate admin user list, create and delete

- package-lock.json
- package.json
- src/app.module.ts
- src/aws/aws.service.ts
- src/email/util/content.util.ts
- src/files/decorators/ReqFiles.decorator.ts
- src/files/files.module.ts
- src/files/files.service.ts
- src/files/files.types.ts
- src/files/interceptors/files.interceptor.ts
- src/main.ts
- src/shared/util/appEnvironment.util.ts
- src/users/schemas/ReadUserOutput.schema.ts
- src/users/schemas/UpdateMetadata.schema.ts
- src/users/users.controller.ts
- src/users/users.module.ts
- src/users/users.types.ts
- src/voterData/voterFile/util/voterFile.util.ts
This adds file uploading to S3 to implement the user avatar upload functionality. 
- Pulled in `@fastify/multipart` to handle multipart form data parsing
- Added `FilesModule` to contain file uploading functions, moved `AwsModule` into the new `FilesModule`
- Implemented `FilesInterceptor` to parse and provide sent files to request handlers
- Implemented `ReqFiles` and `ReqFile` param decorators to pull uploaded files into handler
- Implemented `FilesService` to house file upload/etc functionality
Postman tests: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-141410b5-53b6-4456-8b56-da6e942a2847
> WEB-3437, WEB-3438, WEB-3439: migrate user upload image, user metadata get, user metadata update

- package-lock.json
- package.json
- prisma/schema/campaign.jsonTypes.ts
- src/files/interceptors/files.interceptor.ts
- src/shared/services/slackService.types.ts
- src/shared/util/zod.util.ts
- src/users/users.controller.ts
- src/voterData/util/voterOutreach.util.ts
- src/voterData/voterData.module.ts
- src/voterData/voterFile/schemas/GetVoterFile.schema.ts
- src/voterData/voterFile/schemas/ScheduleOutreachCampaign.schema.ts
- src/voterData/voterFile/voterFile.controller.ts
- src/voterData/voterFile/voterFile.service.ts
- src/voterData/voterFile/voterFile.types.ts
- src/voterData/voterOutreach.service.ts
- Migrates voter file campaign scheduling 
- Also adds a file mimeType validation to the `FilesInterceptor`
> WEB-3428: Nestjs: voter file - schedule

- prisma/migrations/20250203161228_cascade_delete_campaign_with_user/migration.sql
- prisma/schema/campaign.prisma
- src/aws/aws.service.ts
- src/campaigns/positions/campaignPositions.controller.ts
- src/users/users.controller.ts
- some file upload fixes for user avatar upload
- update user / campaign relation to cascade delete
- fixed positionID param name for campaign position endpoints (not completely related, but a bug fix)
Postman tests:
- [Users](https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-019172f4-651d-4c1c-a8b5-9aa60b5b30c4)
- [Campaigns](https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-c3537b7a-54b4-432c-8d54-b0cde49e55cd)
> WEB-3581: Updates for connecting user endpoints to frontend

- src/campaigns/schemas/updateCampaign.schema.ts
- src/declare/declare.controller.ts
- src/declare/declare.service.ts
- src/topIssues/schemas/topIssues.schema.ts
- src/topIssues/topIssues.controller.ts
- src/topIssues/topIssues.service.ts
- src/users/schemas/ReadUserOutput.schema.ts
- src/voters/voterFile/schemas/GetVoterFile.schema.ts
- src/voters/voterFile/voterFile.controller.ts
- fixes issue with declare endpoint not being public and not returning json response
- removes ID param from top issue create + update payloads
- other small fixes
> WEB-3582: fixes for connecting webapp

- src/content/content.service.ts
- src/shared/services/process-timers.service.ts
- src/shared/shared.module.ts
Just figured it could be useful
> Adds a util service to be able to easily time process executions

- src/authentication/authentication.service.ts
- src/users/schemas/ReadUserOutput.schema.ts
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-13c79bb1-0507-43ed-a798-247589660722
> [WEB-3702] - fixes google login and ensures admins can login

- src/content/content.service.ts
- src/content/transformers/faqArticlesTransformer.ts
https://goodparty.atlassian.net/browse/WEB-3717
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-46b0db74-7a9e-4300-b758-5130a744fd72
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/482
> [WEB-3717] - Fixes faq article ids

- prisma/migrations/20250227191100_/migration.sql
- prisma/schema/blogArticleMeta.prisma
- src/campaigns/ai/chat/aiChat.service.ts
- src/campaigns/ai/content/aiContent.controller.ts
- src/campaigns/ai/content/aiContent.service.ts
- src/content/content.controller.ts
- src/content/content.module.ts
- src/content/content.types.ts
- src/content/services/content.service.ts
https://goodparty.atlassian.net/browse/WEB-3706
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-e00f78cb-19cd-42dd-b718-fd27b6d55c4e
> [WE-3706] Blog titles from blogArticleMeta table

- src/campaigns/ai/content/aiContent.service.ts
- src/content/services/content.service.ts
- src/fullStory/fullStory.service.ts
- Update getAiContentPrompts() to query for the right data with the service method through the transformers instead of directly to prisma
- Remove bug where FS would run when disabled
Frontend: https://github.com/thegoodparty/gp-webapp/pull/493
> WEB-3756 & WEB-3763

- src/aws/aws.service.ts
- src/files/files.service.ts
- src/pathToVictory/pathToVictory.controller.ts
- src/pathToVictory/services/pathToVictory.service.ts
- src/queue/consumer/consumer.service.ts
- remove ACL option from s3 upload, 
- small p2v fixes
- Fixed potential undefined p2v error by throwing if it doesnt exist
> WEB-3759: Fix user image upload 

- prisma/migrations/20250309145002_ecanvasser_dashboard/migration.sql
- prisma/schema/ecanvasser.prisma
- src/campaigns/guards/CampaignOwnerOrAdmin.guard.ts
- src/ecanvasser/ecanvasser.controller.ts
- src/ecanvasser/ecanvasser.service.ts
- src/ecanvasser/ecanvasser.types.ts
> Web 3801 ecanvasser dashboard

- src/content/content.controller.ts
https://goodparty.atlassian.net/browse/WEB-3829
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-d378608c-a598-4184-818b-205a3a2a8512
(errors are unrelated)
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/527
> [WEB-3829] - blog article 404s

- src/content/services/content.service.ts
- src/content/transformers/goodPartyTeamMembersTransformer.ts
https://goodparty.atlassian.net/browse/WEB-3837
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-10ab45ff-5a76-4155-88ba-b676b44993ff
UI PR: https://github.com/thegoodparty/gp-webapp/pull/528
> [WEB-3837] - team members fix

- src/shared/util/zod.util.ts
- src/users/schemas/ReadUserOutput.schema.ts
Postman Tests: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-e68b4fc9-76cf-4ac6-a993-1947d51278e0
> WEB-3854: properly handle empty zip and phone when parsing user output

- src/authentication/authentication.service.ts
Postmsn tests: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-8a7b5c50-5d19-48ca-9aa0-5bba2a4a6680
> WEB-3854: obfuscate error message to avoid enumeration attack

- src/aws/aws.service.ts
https://goodparty.atlassian.net/browse/WEB-3858
> [WEB-3858] - Set public-read permission for S3 upload

- src/shared/util/appEnvironment.util.ts
- src/voters/services/voterOutreach.service.ts
- the link was missing the `/api/v1/` piece of the url
> WEB-3857: fix slack voter file url

- src/campaigns/campaigns.module.ts
- src/campaigns/tasks/campaignTasks.consts.ts
- src/campaigns/tasks/campaignTasks.types.ts
- src/campaigns/tasks/campaignTasksController.ts
- src/campaigns/tasks/campaignTasksService.ts
- src/campaigns/tasks/fixtures/tasks-week-1.json
- src/campaigns/tasks/fixtures/tasks-week-2.json
- src/campaigns/tasks/fixtures/tasks-week-3.json
- src/campaigns/tasks/fixtures/tasks-week-4.json
- src/campaigns/tasks/fixtures/tasks-week-5.json
- src/campaigns/tasks/fixtures/tasks-week-6.json
- src/campaigns/tasks/fixtures/tasks-week-7.json
- src/campaigns/tasks/fixtures/tasks-week-8.json
First step for https://goodparty.atlassian.net/browse/WEB-3888
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-842ceb7b-9677-43d7-bcfe-e2ba344ac106
> [WEB-3888] - Initial listing of tasks boilerplate

- src/campaigns/services/crmCampaigns.service.ts
- src/crm/crm.types.ts
- src/crm/schemas/CRMCompanyProperties.schema.ts
- also Fixes some fields that were failing validation on the hubspot sync (strings that should be numbers)
> WEB-3950: Fix Company Name not getting set on HubSpot record

- src/campaigns/tasks/campaignTasks.types.ts
- src/campaigns/tasks/fixtures/tasks-week-1.json
- src/campaigns/tasks/fixtures/tasks-week-2.json
- src/campaigns/tasks/fixtures/tasks-week-3.json
- src/campaigns/tasks/fixtures/tasks-week-4.json
- src/campaigns/tasks/fixtures/tasks-week-5.json
- src/campaigns/tasks/fixtures/tasks-week-6.json
- src/campaigns/tasks/fixtures/tasks-week-7.json
- src/campaigns/tasks/fixtures/tasks-week-8.json
Added couple more fields to task objects for frontend
> WEB-3888: added cta and deadline fields to task data

- src/email/email.types.ts
- src/voters/services/voterOutreach.service.ts
- src/voters/voters.module.ts
https://goodparty.atlassian.net/browse/WEB-3946
Close the loop with candidates who have scheduled a text message so that they know what to expect from the process and don’t annoy Jared.
Requirements
Once a user has scheduled a text campaign, email the candidate
> feat: send email after campaign outreach

- src/campaigns/services/campaigns.service.ts
WebApp PR: https://github.com/thegoodparty/gp-webapp/pull/582
ticket: https://goodparty.atlassian.net/browse/WEB-3690
> Web 3690 verified

- src/elections/schemas/RacesByZip.schema.ts
- src/elections/services/ballotReady.service.ts
- src/elections/services/races.service.ts
Postman run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-7194ab83-1c83-4074-a58f-faf328ffee0e
Companion UI: https://github.com/thegoodparty/gp-webapp/pull/624
> [WEB-3943] - Minor changes for optional field

- .env.example
- src/email/mailgun.service.ts
Added env var to not pollute Mailgun stats with dev,qa, and test data
> feat: new env var to track on prod only

- src/campaigns/services/campaignEmails.service.ts
- src/campaigns/services/crmCampaigns.service.ts
- Turns off the daily countdown task emails
- removes slack @ mentions for scheduled requests
> WEB-4072, WEB-4073

- src/payments/payments.controller.ts
- src/payments/payments.module.ts
- src/payments/services/paymentEventsService.ts
https://goodparty.atlassian.net/browse/WEB-4079
> [WEB-4079] - Detects when user requests cancelation vs api cancel_at being set

- prisma/schema/campaign.jsonTypes.ts
- src/campaigns/schemas/updateCampaign.schema.ts
- src/queue/producer/enqueue.service.ts
- I only added the validation for the details fields for now, in case this causes any other issues. We can add validation like this to all our jsonb fields if it works well
> WEB-4090: validate campaign details json fields

- src/email/email.service.ts
https://goodparty.atlassian.net/browse/WEB-3774
No need for Postman test run email related only.
> [WEB-3774] - Lets Mailgun template details control subject of set-password email

- src/campaigns/ai/content/aiContent.service.ts
- src/pathToVictory/services/enqueuePathToVictory.service.ts
- src/queue/producer/enqueue.service.ts
trying to split sqs messages into groups for concurrency
> WEB-4099: Message groups

- src/campaigns/services/crmCampaigns.service.ts
- src/users/schemas/CreateUserInput.schema.ts
- src/users/services/crmUsers.service.ts
- src/users/services/users.service.ts
https://goodparty.atlassian.net/browse/WEB-3988
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/654
Postman Auth Collection run: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/34024107-c153a871-ad4a-48aa-919d-135e62c44e0b
> [WEB-3988] - Facilitated Signup

- src/admin/users/adminUsers.controller.ts
- src/campaigns/services/crmCampaigns.service.ts
- src/email/mailgun.service.ts
- src/textCampaign/services/rumbleUp.service.ts
- src/textCampaign/services/textCampaign.service.ts
- src/textCampaign/textCampaign.controller.ts
Web PR: https://github.com/thegoodparty/gp-webapp/pull/671
- this completes the basic flow for compliance
- User can submit the PIN, email gets sent to Hubspot company owner's email
- Admins can manually mark as approved or rejected
Postman Tests:
- [Text Outreach](https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-0584a904-ff98-4ecc-a46e-1628dd884a46)
- [Admin Users](https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-22feb2a6-df88-4def-bd5e-77e4d992939a)
> WEB-3970, WEB-4113: compliance pin submission, allow admin manual approve/reject

- prisma/migrations/20250627152640_add_website_contact/migration.sql
- prisma/schema/website.prisma
- prisma/schema/websiteContact.prisma
- seed/factories/websiteContact.factory.ts
- seed/seed.ts
- seed/websiteContacts.ts
- src/shared/schemas/Pagination.schema.ts
- src/websites/controllers/websites.controller.ts
- src/websites/schemas/ContactForm.schema.ts
- src/websites/schemas/GetWebsiteContacts.schema.ts
- src/websites/schemas/UpdateWebsite.schema.ts
- src/websites/services/websiteContacts.service.ts
- src/websites/websites.module.ts
- added WebsiteContact table and some endpoints for capturing form submissions and listing them out
Postman Tests: https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38094541-779ce37a-0b40-414c-8bc1-db5eff746e45
> WEB-4217: basic website contact form capture and list functionality

- src/admin/campaigns/adminCampaigns.controller.ts
- src/authentication/authentication.controller.ts
- src/authentication/authentication.types.ts
- src/shared/services/slackService.types.ts
https://goodparty.atlassian.net/browse/WEB-4324
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/737
> [WEB-4324] - create campaign on register

- src/websites/controllers/websites.controller.ts
- src/websites/schemas/UpdateWebsite.schema.ts
- src/websites/schemas/ValidateVanityPath.schema.ts
- src/websites/schemas/VanityPath.schema.ts
- updates for frontend website creation flow
> WEB-4253: updates for frontend creation ui

- prisma/migrations/20250703105048_add_community_issue_status_log/migration.sql
- prisma/schema/communityIssue.prisma
- prisma/schema/communityIssueStatusLog.prisma
- src/communityIssues/communityIssues.module.ts
- src/communityIssues/controllers/communityIssues.controller.ts
- src/communityIssues/services/communityIssueStatusLog.service.ts
API PR to support status change log:
> feat: status changelog

- prisma/migrations/20250708021856_add_uuid_to_community_issue/migration.sql
- prisma/migrations/20250708234017_make_uuid_primary_key/migration.sql
- prisma/schema/communityIssue.prisma
- prisma/schema/communityIssueStatusLog.prisma
- src/communityIssues/controllers/communityIssues.controller.ts
- src/communityIssues/services/communityIssueStatusLog.service.ts
- src/communityIssues/services/communityIssues.service.ts
This is for the detailed view of the issue. The UUID needs to be in the browser URL, and I didn't want to use the DB ID.
> feat: SRV-17 adding a uuid to community issues

- prisma/schema/website.jsonTypes.ts
- src/websites/controllers/websites.controller.ts
- src/websites/schemas/UpdateWebsite.schema.ts
- src/websites/services/websites.service.ts
> WEB-4358: allow clearing website images, provide some campaign and us…er info for website content

- src/campaigns/campaigns.controller.ts
- src/elections/services/elections.service.ts
It is still unclear the direction where going with the P2V solution, so I've left the election module code in with a TODO for now.
This mostly reverts the files to the previous commit in cases where the district picker commit was the most recent: https://github.com/thegoodparty/gp-api/pull/345
P2V successfully ran with these corresponding webapp changes:
> WEB-4422 Remove Support For District Picker

- src/campaigns/tcrCompliance/campaignTcrCompliance.controller.ts
- src/shared/schemas/Domain.schema.ts
https://goodparty.atlassian.net/browse/WEB-4336
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/792
> [WEB-4341] - adds a minor schema change and endpoint for UI integration

- prisma/migrations/20250724155944_removed_status/migration.sql
- prisma/schema/tcrCompliance.prisma
- src/campaigns/tcrCompliance/campaignTcrCompliance.controller.ts
https://goodparty.atlassian.net/browse/WEB-4341
Companion UI PR: https://github.com/thegoodparty/gp-webapp/pull/796
> [WEB-4341] - Updates pending status for TcrCompliance on CV token retrieval

- src/voters/voterFile/util/voterFile.util.ts
- src/voters/voterFile/voterFile.types.ts
https://goodparty.atlassian.net/browse/WEB-4408
> [WEB-4408] - Fixes landlines vs cell numbers in robocall voter files

- prisma/schema/domain.prisma
- src/websites/controllers/domains.controller.ts
FE: https://github.com/thegoodparty/gp-webapp/pull/807
> WEB-4441-cleanup

- src/campaigns/campaigns.controller.ts
- src/campaigns/services/campaigns.service.ts
- src/elections/services/elections.service.ts
- src/shared/services/slack.service.ts
- src/shared/util/appEnvironment.util.ts
https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/38601784-7bc7b730-b25e-4723-868e-0ff21a0bbd65
> DT-132 - Mass Update Win Numbers Endpoint

- .env.example
- deploy/sst.config.ts
- src/analytics/analytics.controller.ts
- src/analytics/analytics.service.ts
- src/analytics/analytics.types.ts
- src/campaigns/services/campaigns.service.ts
- src/campaigns/services/crmCampaigns.service.ts
- src/crm/crm.types.ts
- src/crm/hubspot.service.ts
- src/users/services/users.service.ts
on top of removing fullstory integration, I also created a mock hubspot client so we stop getting all the noise if slack like this:
> chore: remove fullstoy integration

- deploy/Dockerfile
Deployment was failing with ECS service timeout error:
```
Waiter ServicesStable failed: Max attempts exceeded
```
The ECS service was not reaching a stable state because health checks were failing.
[PR #389](https://github.com/thegoodparty/gp-api/pull/389) restructured the Prisma schema to use **multi-file schemas** with the new `prismaSchemaFolder` preview feature:
- **Schema files moved**: From single `prisma/schema.prisma` to multiple files in `prisma/schema/` directory
- **Migrations relocated**: From `prisma/migrations/` to `prisma/schema/migrations/` 
- **New structure**: Uses `previewFeatures = ["prismaSchemaFolder"]` in `prisma/schema/schema.prisma`
However, the **Dockerfile was not updated** to handle this new schema structure, causing:
- Database migrations to fail during …
> fix: update dockerfile

- TEAM_SETUP.md
- deploy/Dockerfile
- package-lock.json
- package.json
ECS deployments were failing with timeout errors:
```
Waiter ServicesStable failed: Max attempts exceeded
```
The service could not reach a stable state due to container startup failures.
Through investigation, we discovered **multiple layered issues**:
- Initially suspected [PR #389](https://github.com/thegoodparty/gp-api/pull/389) schema restructuring
- PR #389 moved from single `schema.prisma` to multi-file schema structure
- **This was not the actual issue** - just a red herring
- Application was crashing on startup with:
```
TypeError: Class extends value undefined is not a constructor or null
at @langchain/community/dist/chat_models/togetherai.cjs:373:39
```
- **Fixed** by updating LangChain package versions to compatible ranges
- Docker builds failing with hundreds of dependency …
> chore: peer dependency

- src/campaigns/campaigns.controller.ts
https://goodpartyorg.postman.co/workspace/GP-API~66e2b59d-bf6a-4380-81c2-1cbf2d01bddf/run/45943326-52a12db9-7d14-48c6-93f8-e6573ee9200f
> Allow admin/sales to update race-target-details for any campaign

- src/analytics/analytics.service.ts
- src/campaigns/ai/content/aiContent.controller.ts
- src/queue/consumer/queueConsumer.module.ts
- src/queue/consumer/queueConsumer.service.ts
- src/segment/segment.service.ts
- src/segment/segment.types.ts
https://goodparty.atlassian.net/browse/WEB-4398
UI companion PR: https://github.com/thegoodparty/gp-webapp/pull/894
> [WEB-4398] - Compliance completed analytics event and identity profile update

- src/campaigns/campaigns.controller.ts
- src/campaigns/tcrCompliance/campaignTcrCompliance.controller.ts
- src/peerly/p2p.controller.ts
- src/peerly/peerly.module.ts
- src/peerly/schemas/p2pPhoneListRequest.schema.ts
- src/peerly/schemas/p2pPhoneListResponse.schema.ts
- src/peerly/schemas/p2pPhoneListStatus.schema.ts
- src/peerly/services/p2pPhoneListUpload.service.ts
- src/peerly/utils/audienceMapping.util.ts
- src/shared/modules/voterShared.module.ts
- src/shared/types/voter.types.ts
- src/voters/services/voterFileFilter.service.ts
- src/voters/voterFile/voterFile.types.ts
- src/voters/voters.module.ts
A circular dependency fix was omitted from previous PR (https://github.com/thegoodparty/gp-api/pull/459) and had to be reverted. This revised PR includes the circular dependency fix.
> [WEB-4345] Peerly voter file upload

- package-lock.json
- src/campaigns/tcrCompliance/schemas/createTcrComplianceDto.schema.ts
- src/peerly/services/peerlyIdentity.service.ts
- src/shared/util/strings.util.ts
https://goodparty.atlassian.net/browse/WEB-4558?focusedCommentId=21696
support for webapp PR: https://github.com/thegoodparty/gp-webapp/pull/924
> [WEB-4558] - API validation for filing url

- src/campaigns/tcrCompliance/services/campaignTcrCompliance.service.ts
- src/vendors/peerly/services/peerlyIdentity.service.ts
- src/websites/services/domains.service.ts
- src/websites/websites.module.ts
https://goodparty.atlassian.net/browse/WEB-4617
> [WEB-4617] - integrates vercel and forwardEmail services w/ domain purchase flow

- src/peerly/services/peerlyIdentity.service.ts
Wrong endpoint in our code. This corrects that.
> [HOTFIX] - fixes CV token submission. Hopefully 🤞
